# 1)import the numpy package under the name np

In [120]:
import numpy as np    #importing the numpy library

# 2)create a null vector of size 10

In [3]:
a = np.zeros(10)   #np.zeros gives all zeros as output
print(a)          #we can also write only "a" but the output will be"array[.......]"


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#to find the size of vector
a.size 

10

# 3)create a null vector of size 10 but the fifth value is 1

In [10]:
a = (np.arange(10)==4).astype(int) #it gives an array all false(0)except for fourth position i,e..true(1)
print(a)


[0 0 0 0 1 0 0 0 0 0]


# 4)create a vector values ranging from 10to49

In [11]:
b = np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# 5)reverse a vector

In [23]:
b = b[::-1]
b

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

# 6)create a 3x3 matrix with values ranging from 0 to 8

m = np.arange(0,9)
m.reshape(3,3)

# 7)Find indices of nonzero elements from [1,2,0,0,4,0]

In [46]:
a = [1,2,0,0,4,0]
nonzeroind = np.nonzero(a)
print(nonzeroind)

(array([0, 1, 4], dtype=int64),)


# 8)Create a 3x3x3 array with random values

In [51]:
a1 = np.random.random((3,3,3))
print(a1)

[[[0.74759761 0.23991381 0.18269427]
  [0.84438864 0.82080761 0.34849578]
  [0.97470728 0.97728551 0.3512262 ]]

 [[0.5904945  0.50131372 0.9937086 ]
  [0.30110534 0.10118876 0.89399327]
  [0.15892719 0.06741323 0.43565532]]

 [[0.96255493 0.19944939 0.38247628]
  [0.43323255 0.89491172 0.67214216]
  [0.93219083 0.04563736 0.71736047]]]


# 9)Create a random vector of size 30 and find the mean value

In [85]:
a2 = np.arange(30)
print(a2)
print("\n\n mean of range 30 is",a2.mean())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


 mean of range 30 is 14.5


# 10)Create a 2d array with 1 on the border and 0 inside

In [122]:
array = np.ones((4,4))     #4*4 matrix
print("original array:")   #4*4 matrix all the values are filled with 1
print(array,"\n\n")
print("1 on the border and o inside the array:")
array[1:3,1:3]=0      #[1:3,1:3]=0 it indicates that after the 1st index and before 3rd index in row/column values are zero 
print(array)

original array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 


1 on the border and o inside the array:
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


# 11)Create an 8x8 matrix and fill it with a checkerboard pattern

In [78]:
x = np.ones((8,8))
print("checkerboard pattern:")
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
#slice from 1st index row till 1+2+2+..and fill all the columns with 1 starting from 0th to 0+2+2..
x[::2,1::2]=1
#slice from the 0th row till 0+2+2.. and fill all the columns with 1 strating from 1 to 1+2+2
print(x)

checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 12)What is the major difference between sets, lists, tuples, and dictionaries?

In [ ]:
#differences between list,tuples,sets,and dictionaries
#list
'''1)list is a collection which is orderd.
2)lists are mutable and allows the duplicate values.
3)square brackets are used to represent the list  []. 
4)we can single element at the end by without changing or modifying the list.'''
#tuples
'''1)tuples is an orderd collection
2)tuples are immutable
3)Tuples are enclosed within parenthesis.()
4)an element cannot be added to the tuple as it is immutable.'''
#sets
'''1)sets is an unorderd collection.
2)Sets are mutable and have no duplicate elements.
3)Sets are represented in curly brackets {}.
4)The set add() method adds a given element to a set.'''
#dictionaries
'''1) dictionary is an unordered collection of data that stores data in key-value pairs.
2)this are mutable and keys do not allow duplicates {}.
3)dictionaries are enclosed in curly brackets in the form of key-value pairs.
4)it can changed or modifyed with the specified key-value pairs'''


# 13)Print first 10 natural numbers using while loop

In [86]:
i = 1
while(i<=10):
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9
10


# 14)Print the numbers -10 to -1 using for loop.

In [108]:
for i in range(-10,0):
        print(i)
        

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


# 15)Print the message "Done" after successful execution of any for a loop.

In [123]:
for i in range(-10,0):
    print(i)
if i==-1:
    print("done")
else:
    print("not done")

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
done


# 16)Create a random vector of size 10 and sort it

In [124]:
a2 = np.random.random((10))
print("before sorting=",a2,"\n\n")
a3 = a2
a3.sort()
print("after sorting=",a3)

before sorting= [0.01364208 0.88210601 0.42038992 0.9133489  0.53287671 0.02895712
 0.50231628 0.22569463 0.4117177  0.99847326] 


after sorting= [0.01364208 0.02895712 0.22569463 0.4117177  0.42038992 0.50231628
 0.53287671 0.88210601 0.9133489  0.99847326]


# 17)Execute any three math functions using Numpy.

In [126]:
import math as m #importing math library as m

In [131]:
x =45 #square root of 45
x =np.sqrt(x)
print(x)

6.708203932499369


In [130]:
x = 45       #sin functiom
x = np.sin(45)
print(x)

0.8509035245341184


In [133]:
x = np.arange(0,5) #sin value from range of 0 to 5
x= np.sin(x)
print(x)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [132]:
x =10      #logarithmic function
x =np.log(x)
print(x)

2.302585092994046
